// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umlqppsngnjkpxdtybbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbHFwcHNuZ25qa3B4ZHR5YmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDYzMjYsImV4cCI6MjA1OTg4MjMyNn0.WvJx6_7ALaPn1sZqOyYgpHFFWCLjNDVu2wh2I3twUwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);